# Generated by Django 5.1.3 on 2024-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('attachment', models.FileField(null=True, upload_to='media/attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
