# Generated by Django 5.0.7 on 2024-08-06 17:40

import upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=upload_to.UploadTo('media/attachments'))),
            ],
        ),
    ]
